# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [4]:
x=s.split()


['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [5]:
planet = "Earth"
diameter = 12742

In [6]:
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [10]:
x=d.items()

# Numpy

In [11]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [12]:
array=np.zeros(10)

In [13]:
arr=np.ones(10)*5

## 5. Create an array of all the even integers from 20 to 35

In [15]:
a=np.arange(20,35,2)


[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
mat =  np.arange(0, 9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [23]:
a = np.array([1, 2, 3])
b = np.array([4, 5,6])
np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [18]:
import pandas as pd


In [24]:
students=[["vishnu",20],["vishwa",19],["saran",20]]

df = pd.DataFrame(students,columns=['Name', 'Age'])

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [25]:
per1 = pd.date_range(start ='1-1-2023', 
         end ='10-02-2023', freq ='1D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [26]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [27]:
dataframe = pd.DataFrame(lists, columns =['s.no', 'name','age']) 